### Práctica de Acceso a bases de datos

Considerar una base de datos sobre diferentes índices bursatiles formada por las siguientes tablas:

__Tabla "Datos generales"__:

* Ticker (Valor único) Cadena	
* Nombre Cadena	
* Índice Cadena	
* País Cadena		

__Tabla "IBEX35"__:

* TKR (Valor único y hace referencia al campo Ticker de la tabla Datos generales)  Cadena	
* Precio Decimal
* Var.(%) Decimal
* Var.(€) Decimal
* Máx. Decimal
* Mín. Decimal
* Volumen Entero

__Tabla "DAX30"__:

* TKR (Valor único y hace referencia al campo Ticker de la tabla Datos generales)  Cadena	
* Precio Decimal
* Var.(%) Decimal
* Var.(€) Decimal
* Máx. Decimal
* Mín. Decimal
* Volumen Entero

__Tabla "NASDAQ100"__:

* TKR (Valor único y hace referencia al campo Ticker de la tabla Datos generales)  Cadena	
* Precio Decimal
* Var.(%) Decimal
* Var.(€) Decimal
* Máx. Decimal
* Mín. Decimal
* Volumen Entero

__Tabla "FTSE_MIB"__:

* TKR (Valor único y hace referencia al campo Ticker de la tabla Datos generales)  Cadena	
* Precio Decimal
* Var.(%) Decimal
* Var.(€) Decimal
* Máx. Decimal
* Mín. Decimal
* Volumen Entero

__Tabla "SemanalesIBEX35"__:

* Ticker (Valor único y hace referencia al campo Ticker de la tabla Datos generales)  Cadena	
* Fecha Cadena
* Price Decimal
* Low Decimal
* High Decimal

Los datos de las tablas se encuentran en los archivos csv "Tabla1.csv", "Tabla2(IBEX35).csv", "Tabla3(DAX30).csv", "Tabla4(Nasdaq 100).csv", "Tabla5(Ftse Mib).csv" y "Tabla6(SemanalesIBEX35).csv".La tabla 1 contiene datos identificativos de cada acción, las tablas 2-5 son los resultados de la cotización el día 5 de octubre de 2022, y la tabla 6 son datos históricos de las acciones del IBEX35.

Se pide:
1.  Hacer una función que cree la base de datos "Bolsa" con sus tablas y datos correspondientes. Para ello habrá que procesar los archivos csv proporcionados.Tomar las decisiones necesarias para relacionar adecuadamente las tablas, así como restricciones en cuanto a unicidad o tipos de datos. Igualmente procesad adecuadamente el campo fecha de la tabla "SemanalesIBEX35"para poder utilizarlo en las consultas(3 puntos).

2.  Resolver las siguientes consultas(7 puntos):

* Considerar la máxima diferencia entre el valor máximo y el valor mínimo de las acciones de todos los índices. Mostrar el nombre de la/s acción/es cuya diferencia alcanza ese valor, el nombre del indice al que pertenece y el valor de la diferencia tomada

* Obtener la suma de los volumenes negociados agregados por el índice al que pertenecen y ordenados de mayor a menor. Se mostrará el nombre del índice, el país al que pertenece y la suma de los volúmenes del índice.

* Obtener aquellas acciones cuyo variación entre el máximo y el mínimo en la jornada del 5 de octubre fue menor que la variacion entre el valor low y high en la serie histórica. Mostrar el nombre de la acción y las diferencias.

* Obtener la media de los valores de las acciones de la serie histórica del IBEX35 ordenadas decrecientemente por la media de los valores.

* Obtener la acción que más valió y más volumen de titulos negoció en la jornada del 5 de octubre. Mostrar el nombre de la acción, el índice al que pertenece y el pais.

* Obtener las diferencias de precio entre cada par de acciones en la serie histórica del IBEX35 por fecha. Mostrar el nombre de las accciones, la fecha y la diferencia de valor ordenadas decrecientemente por la fecha.

* ¿En que fecha de la serie histórica del IBEX35 hubo más acciones donde la diferencia entre el valor maximo y el precio final fue 0?
  Mostrar los nombres de las acciones y la fecha.
  
#### Normas de entrega

* Fecha tope de entrega: 13/10/2022
* La entrega se realizará subiendo al campus virtual un notebook de Jupyter con la solución. El archivo tendrá como nombre BasesDatos_GrupoX donde X será el número de grupo correspondiente.

In [9]:
import sqlite3
import csv

def leerDatosGenerales():
    csvarchivo = open('Tabla1.csv',encoding="iso-8859-1",errors='ignore')
    entrada = csv.reader(csvarchivo, delimiter=";")
    tabla = list(entrada)
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()
    cur.execute("DROP TABLE IF EXISTS Datos")
    cur.execute("CREATE TABLE Datos (Ticker TEXT UNIQUE, Nombre TEXT, Indice TEXT, Pais TEXT)")
    for fila in tabla[1:]:
        cur.execute("INSERT INTO Datos VALUES (?,?,?,?)", fila)   
    cur.close()
    conn.commit()

def leerDatosIbex():
    csvarchivo = open('Tabla2(IBEX35).csv',encoding="iso-8859-1",errors='ignore')
    entrada = csv.reader(csvarchivo, delimiter=";")
    tabla = list(entrada)
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()
    cur.execute("DROP TABLE IF EXISTS Ibex")
    cur.execute("CREATE TABLE Ibex (Ticker TEXT REFERENCES Datos(Ticker) UNIQUE, Precio DOUBLE, VarPorcentaje DOUBLE, VarAbsoluto DOUBLE, Max DOUBLE, Min DOUBLE, Volumen INTEGER)")
    for fila in tabla[1:]:
        cur.execute("INSERT INTO Ibex VALUES (?,?,?,?,?,?,?)", fila)   
    cur.close()
    conn.commit()


def leerDatosDAX30():
    csvarchivo = open('Tabla3(DAX 30).csv',encoding="iso-8859-1",errors='ignore')
    entrada = csv.reader(csvarchivo, delimiter=";")
    tabla = list(entrada)
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()
    cur.execute("DROP TABLE IF EXISTS DAX30")
    cur.execute("CREATE TABLE DAX30 (Ticker TEXT REFERENCES Datos(Ticker) UNIQUE, Precio DOUBLE, VarPorcentaje DOUBLE, VarAbsoluto DOUBLE, Max DOUBLE, Min DOUBLE, Volumen INTEGER)")
    for fila in tabla[1:]:
        cur.execute("INSERT INTO DAX30 VALUES (?,?,?,?,?,?,?)", fila)
    cur.close()
    conn.commit()
    
def leerDatosNasdaq100():
    csvarchivo = open('Tabla4(Nasdaq 100).csv',encoding="iso-8859-1",errors='ignore')
    entrada = csv.reader(csvarchivo, delimiter=";")
    tabla = list(entrada)
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()
    cur.execute("DROP TABLE IF EXISTS Nasdaq100")
    cur.execute("CREATE TABLE Nasdaq100 (Ticker TEXT REFERENCES Datos(Ticker) UNIQUE, Precio DOUBLE, VarPorcentaje DOUBLE, VarAbsoluto DOUBLE, Max DOUBLE, Min DOUBLE, Volumen INTEGER)")
    for fila in tabla[1:]:
        cur.execute("INSERT INTO Nasdaq100 VALUES (?,?,?,?,?,?,?)", fila)   
    cur.close()
    conn.commit()
    
def leerDatosFtseMib():
    csvarchivo = open('Tabla5(Ftse Mib).csv',encoding="iso-8859-1",errors='ignore')
    entrada = csv.reader(csvarchivo, delimiter=";")
    tabla = list(entrada)
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()
    cur.execute("DROP TABLE IF EXISTS FtseMib")
    cur.execute("CREATE TABLE FtseMib (Ticker TEXT REFERENCES Datos(Ticker) UNIQUE, Precio DOUBLE, VarPorcentaje DOUBLE, VarAbsoluto DOUBLE, Max DOUBLE, Min DOUBLE, Volumen INTEGER)")
    for fila in tabla[1:]:
        cur.execute("INSERT INTO FtseMib VALUES (?,?,?,?,?,?,?)", fila)   
    cur.close()
    conn.commit()
def leerDatosSemanalesIBEX():
    csvarchivo = open('Tabla6(SemanalesIBEX35).csv',encoding="iso-8859-1",errors='ignore')
    entrada = csv.reader(csvarchivo, delimiter=";")
    tabla = list(entrada)
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()
    cur.execute("DROP TABLE IF EXISTS SemanalesIBEX35")
    cur.execute("CREATE TABLE SemanalesIBEX35 (Ticker TEXT REFERENCES Datos(Ticker), Fecha TEXT, Price DOUBLE, Low DOUBLE, High DOUBLE)")
    for fila in tabla[1:]:
        cur.execute("INSERT INTO SemanalesIBEX35 VALUES (?,?,?,?,?)", (fila[0], fila[1].split()[0], fila[2], fila[3], fila[4]))   
    cur.close()
    conn.commit()

def crearBaseDatos():
    leerDatosGenerales()
    leerDatosIbex()
    leerDatosDAX30()
    leerDatosNasdaq100()
    leerDatosFtseMib()
    leerDatosSemanalesIBEX()

def consulta1():
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()

    query = """SELECT Nombre, Indice, Max - Min FROM
               (SELECT * from DAX30
                       UNION SELECT * FROM FtseMib
                       UNION SELECT * FROM Ibex
                       UNION SELECT * FROM Nasdaq100)
                       JOIN Datos USING(Ticker)
               WHERE Max - Min == (SELECT MAX(Max - Min) FROM
                                       (SELECT * from DAX30
                                           UNION SELECT * FROM FtseMib
                                           UNION SELECT * FROM Ibex
                                           UNION SELECT * FROM Nasdaq100));"""

    for row in cur.execute(query):
        print(row)

    cur.close()

def consulta2():
    conn=sqlite3.connect("bolsa.sqlite3")
    cur=conn.cursor()

    query = """SELECT Indice, Pais, SUM(Volumen) FROM
                Datos JOIN (SELECT * from DAX30
                    UNION SELECT * FROM FtseMib
                    UNION SELECT * FROM Ibex
                    UNION SELECT * FROM Nasdaq100) USING(Ticker)
                GROUP BY Indice;"""

    for row in cur.execute(query):
        print(row)

    cur.close()

def consulta3():
    pass

def consulta4():
    pass

def consulta5():
    pass

def consulta6():
    pass

def consulta7():
    pass

In [7]:
crearBaseDatos()

['ANA', '122.80', '-2.69', '-3.40', '127.44', '121.92', '775574']
['ACX', '93.37', '-1.43', '-1.35', '94.95', '92.81', '258284']
['ACS', '166.12', '-0.65', '-1.08', '166.56', '164.96', '569424']
['AENA', '41.91', '-0.91', '-0.38', '42.22', '41.38', '2384098']
['AMS', '48.65', '0.01', '0.01', '49.32', '48.59', '2265672']
['MTS', '71.47', '-1.89', '-1.38', '72.59', '70.64', '1540008']
['BBVA', '101.00', '0.15', '0.15', '102.00', '1.25', '206950']
['SAB', '64.78', '-1.55', '-1.02', '65.58', '64.30', '270011']
['SAN', '46.31', '-5.57', '-2.73', '48.80', '45.49', '965641']
['BKT', '31.53', '-1.47', '-0.47', '32.00', '31.25', '1114406']
['CABK', '24.43', '-1.43', '-0.35', '24.88', '24.08', '1116829']
['CLNX', '7.93', '-1.69', '-0.13', '8.14', '7.90', '10868838']
['ANE', '173.70', '1.28', '2.20', '174.15', '171.30', '337321']
['ENG', '32.00', '-2.33', '-0.76', '32.71', '31.83', '2166362']
['ELE', '17.95', '-2.47', '-0.45', '18.30', '17.92', '5147082']
['FER', '8.06', '-2.23', '-0.18', '8.25', '8.20', '3994450']
['FDR', '21.74', '-3.59', '-0.81', '22.41', '21.63', '1420189']
['GRF', '28.37', '-4.83', '-1.44', '29.45', '28.32', '684957']
['IAG', '159.50', '0.54', '0.85', '159.75', '158.45', '74288']
['IBE', '42.06', '-2.84', '-1.23', '43.03', '41.71', '440558']
['ITX', '62.02', '-0.58', '-0.36', '62.48', '61.42', '475973']
['IDR', '25.48', '3.12', '0.77', '25.89', '24.63', '6823637']
['COL', '285.80', '-0.59', '-1.70', '288.40', '284.60', '427496']
['ROVI', '53.01', '-3.62', '-1.99', '54.55', '52.30', '2697461']
['MAP', '173.10', '-0.37', '-0.65', '175.25', '172.45', '203278']
['MEL', '159.90', '-0.78', '-1.25', '161.80', '158.20', '68034']
['MRL', '258.00', '0.58', '1.50', '258.40', '255.50', '353092']
['NTGY', '59.60', '-1.16', '-0.70', '60.44', '57.96', '1032478']
['PHM', '49.38', '-2.10', '-1.06', '51.24', '49.11', '373718']
['RED', '43.87', '-0.14', '-0.06', '44.17', '43.68', '311286']
['REP', '40.11', '1.08', '0.43', '40.41', '39.82', '1952046']
['SCYR', '87.24', '-1.43', '-1.27', '88.40', '86.79', '1418315']
['SGRE', '391.40', '-3.43', '-13.90', '411.80', '390.90', '83602']
['SLR', '104.24', '-1.96', '-2.08', '106.16', '103.28', '1342958']
['TEF', '11.51', '-5.62', '-0.69', '12.15', '11.28', '2030401']

In [3]:
consulta1()

('INTUIT INC', 'Nasdaq 100', 412.65)

In [10]:
consulta2()

('Ftse Mib', 'Italia', 395854403)
('IBEX 35', 'España', 186454088)
('Nasdaq 100', 'USA', 842896255)

In [ ]:
consulta3()

In [ ]:
consulta4()

In [ ]:
consulta5()

In [ ]:
consulta6()

In [ ]:
consulta7()